small fixes
timas130/bonfire pull request #11
Opened 2024-11-27 18:08 UTC by Camper-CoolDie

* При нажатии на картинку в таблице открывается экран просмотра картинок, причём можно перелистывать все картинки из одной таблицы (раньше при нажатии ничего не происходило)
* Все ссылки bonfire.moe в `ControllerExternalLinks.openLink()` будут сразу открываться без предупреждения (не работает для поддоменов)
* Чтобы изменить статус надо нажать на карандашик справа, если нажать на текст то ничего не будет (сделал по аналогии с описанием)

2024-11-27 18:24 UTC, timas130 requested changes
Не собирал приложение, но вроде в целом норм. Посмотрю и солью, когда закончу своё.

2024-11-27 18:24 UTC, timas130 commented on CampfireSDK/src/main/java/com/sayzen/campfiresdk/compose/publication/post/pages/TablePage.kt
> +    }
```suggestion
    val images = remember(page) {
        val ret = mutableListOf<ImageRef>()
        for (cell in page.cells) {
            if (cell.image.isEmpty()) {
                continue
            }
            images.add(cell.image)
        }
        ret.toList()
    }

     var imageIndex = 0
```
^ Не проверял. Короче надо через `remember` сделать.

2024-11-27 18:24 UTC, timas130 commented on CampfireSDK/src/main/java/com/sayzen/campfiresdk/screens/account/profile/CardStatus.kt
>          val vStatusContainer: View = view.findViewById(R.id.vStatusContainer)
vStatusContainer можно выпилить полностью вместе с его id в layout'е.

2024-11-27 18:31 UTC, Camper-CoolDie commented on CampfireSDK/src/main/java/com/sayzen/campfiresdk/screens/account/profile/CardStatus.kt
>          val vStatusContainer: View = view.findViewById(R.id.vStatusContainer)
Он нужен, чтобы держать карандашик и сам текст на одном уровне. Можно просто айди убрать, он нигде не используется

2024-11-27 19:05 UTC, timas130 approved these changes
Гуд. Солью когда проверю и закончу BON-224.

2024-11-27 19:19 UTC, timas130 approved these changes

2024-12-22 19:40 UTC, timas130 reviewed
Верю, что норм

2024-12-22 19:40 UTC, timas130 approved these changes

2024-12-22 19:40 UTC, merged