feat: better link following alert (BON-190)
timas130/bonfire pull request #7
Opened 2024-09-21 20:44 UTC by Camper-CoolDie

2024-09-22 15:51 UTC, timas130 requested changes

2024-09-22 15:51 UTC, timas130 commented on CampfireSDK/src/main/java/com/sayzen/campfiresdk/compose/other/LinkAlert.kt
> +                )
Wth, можно просто backgound на родительском боксе прописать и всё

2024-09-22 15:51 UTC, timas130 commented on CampfireSDK/src/main/java/com/sayzen/campfiresdk/controllers/ControllerLinks.kt
> +        val linkHost = URI(link).getHost() ?: ""
Может крашнуть, если вдруг ссылка не запарсится

2024-09-22 15:51 UTC, timas130 commented on CampfireSDK/src/main/java/com/sayzen/campfiresdk/compose/other/LinkAlert.kt
> +) : ComposeSplash() {
В целом имеет больше смысла передавать сразу спаршенный uri, а не делать странные вывороты с link и linkHost

2024-09-22 15:51 UTC, timas130 commented on CampfireSDK/src/main/java/com/sayzen/campfiresdk/compose/other/LinkAlert.kt
> +                    Spacer(Modifier.width(6.dp))
Лучше сделать `horizontalArrangement = Arrangement.spacedBy(6.dp)`, чтобы не создавать лишний элемент

2024-09-22 15:51 UTC, timas130 commented on CampfireSDK/src/main/java/com/sayzen/campfiresdk/compose/other/LinkAlert.kt
> +                )
Если ссылка длинная, то она растянется на несколько строк. Лучше сделать `textOverflow = TextOverflow.Ellipsis, maxLines = 1, softWrap = false` (вроде так)

2024-09-22 17:39 UTC, Camper-CoolDie commented
Я решил передавать ссылку ввиде строки, потому что она нам ещё пригодится при создании AnnotatedString

2024-09-25 14:35 UTC, timas130 requested changes

2024-09-25 14:35 UTC, timas130 commented on CampfireSDK/src/main/java/com/sayzen/campfiresdk/compose/other/LinkAlert.kt
> +    val hostIndex = link.indexOf(string = host, ignoreCase = false)
Может случиться баг, если есть auth часть в ссылке. Например: `https://example.com:password@example.com/`. Можно либо эту часть убрать из показа ссылки, либо просто подсвечивать домен.

2024-09-25 14:35 UTC, timas130 commented on CampfireSDK/src/main/java/com/sayzen/campfiresdk/controllers/ControllerLinks.kt
> +            err(e)
Нужен какой-то фидбек, если ссылку не удалось открыть. Какой-нибудь ToolsToast

2024-09-25 14:35 UTC, timas130 commented on CampfireSDK/src/main/java/com/sayzen/campfiresdk/controllers/ControllerLinks.kt
> +    }
Лучше либо все новые части + `openLink` перенести в новый файл, либо эту часть вверх перенести, потому что она как-то далеко от основной части. В целом ControllerLinks больше относится к ссылкам в приложение, а не из него, так что лично я склоняюсь к первому варианту.

2024-10-10 19:42 UTC, timas130 approved these changes
Радикально, I love it. Днём солью

2024-10-18 09:51 UTC, merged